# 3: Logistic regression

### 

The data consists of two data sets retrieved from the UCI Machine Learning Repository using Student performance dataset from https://archive.ics.uci.edu/ml/datasets/Student+Performance. The data attributes include student grades, demographic, social and school related features and it was collected by using school reports and questionnaires. Two datasets are provided regarding the performance in two distinct subjects: Mathematics (mat) and Portuguese language (por). One table was students from a math course, and the other students from Portuguese course. The two datasets were combined for this analysis.

The data consists of 382 obsevations (students) and 35 variables. The 35 column names are as follows:

```{r, echo=FALSE}

alc2 <- read.csv(file = "/Users/mikko/Documents/GitHub/IODS-project/data/alc.csv", header = T, sep=",")
colnames(alc2)
```

Two variables are describing the student's alcohol use. The variable "alc_use" is the average alcochol use on weekdays and weekends together. The variable "high_use" indicates if the average alcohol use is more than 2.

I chose 4 variables that I believe to have some relationship with the alcohol consumption. The variables are "sex", "studytime", "activities" and "romantic". The gender ("sex"), extra-curricular activities ("activities") and relationship status ("romantic") are binary variables. Weekly studytime is numeric varying in 4 different categories between 1 and 10 hours. I would hypothesize that males, those who do not have extra-curricular activities, those who are not in a romantic relationship, and those with lower amounts of weekly studytime, have higher probability to high use alcohol consumption. 

### *Tables and numeric evaluation of the relationships*

I think a barplot will describe the relationships quite well.

```{R}
library(ggplot2)
g1<-ggplot(data = alc2, aes(x = alc_use))
g1 <- g1 + geom_bar(aes(fill=sex))
g1

```

It can clearly be seen from the plot that males are the majority in larger means of alcohol consumption. This is especially clear when the mean value is 3 or higher. 

